# FROM ubuntu:24.04

# WORKDIR /usr/src/app

# # 18version install
# # RUN apt-get update && apt-get -y install nodejs

# # curl install
# RUN apt-get update && apt-get -y install curl
# # node install
# RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - &&\
# apt-get install -y nodejs

# # react install
# RUN yes | npx create-react-app /usr/src/app
# # RUN yes | npx create-react-app app

# # CMD ["npm", "run", "start"]

# FROM node:latest
# WORKDIR /usr/src/app

FROM node:latest
WORKDIR /usr/src/app